### ISSUE TITLE
shouldReceiveRequest != shouldRevieveRequest

### ISSUE THREAD

**Issue by stephenwf** [aerisweather/GuzzleHttpMock#1]
Just thought I'd mention that there is a misspelling in the read me.

**Comment by stephenwf** [comment]
Another one. I may just raise a pull request if I find any more.

andResponseWithJson

to

andRespondWithJson

**Comment by eschwartz** [comment]
just goes to show you that IDEs with autocomplete make you lazy :)

Thanks!

**Comment by stephenwf** [comment]
Found another :) 

https://github.com/aerisweather/GuzzleHttpMock#mocking-responses

andResponsdWithJson -> andRespondWithJson

**Comment by eschwartz** [comment]
turns out I have this little thing called a "spell-checker" in my IDE. Maybe I should use that more often....
